### ISSUE TITLE
Bad configure script

### ISSUE THREAD

**Issue by maxice8** [jjk-jacky/pam_rundir#1]
the [configure](https://github.com/jjk-jacky/pam_rundir/blob/master/configure) script calls for /bin/sh in it's shebang but actually uses bashisms which leads to the following error when called via Dash (voidlinux) and Busybox Ash (Alpine)

```
./configure: 53: ./configure: Bad subtitution
```

A fix would be calling /usr/bin/env bash or fixing the problem which a shellcheck look reveals to be

```
Line 53:
if [ "${prefix:$l}" = "/" ]; then
      ^-- SC2039: In POSIX sh, string indexing is undefined.
 
Line 54:
    prefix=${prefix:0:$l}
           ^-- SC2039: In POSIX sh, string indexing is undefined.
```

[SC2039](https://github.com/koalaman/shellcheck/wiki/SC2039)

**Comment by jjk-jacky** [comment]
Just pushed a fix, thanks.
