### ISSUE TITLE
Unreliable creation of runtime dirs

### ISSUE THREAD

**Issue by maxice8** [jjk-jacky/pam_rundir#2]
Sometimes creation of the user runtimedir doesn't happen, only the .$uid file is created and the variable is not set.

Reproducing: 

- Add 'session	   optional   pam_rundir.so' to `/etc/pam.d/system-login`
- Restart system and try logging in on a tty

Result:

- File .$uid is created
- no runtime dir is created or variable set

The temporary solution is to close all sessions and remove /run/user with rm -rf, the second time it will create it correctly, doing this when it's working correctly will also cause it to not work

**Comment by jjk-jacky** [comment]
hmm, so I don't have much time lately, unfortunately, but I'm not sure I
can reproduce it. At least I don't see it, I mean I login and everything
works fine from the first time, I don't ever have to remove anything...

So you're saying on boot/first login, /run/users/.$UID is created, but
there's no folder /run/users/$UID; correct? What's the content of
the .$UID file?

**Comment by maxice8** [comment]
> So you're saying on boot/first login, /run/users/.$UID is created, but
there's no folder /run/users/$UID; correct? What's the content of
the .$UID file?

Sometimes on reboot and sometimes after closing all user sessions ( logging out everywhere ) and logging in again, but it does seem to be getting rarer and rarer. also deleting the .$uid file and removing all sessions and starting a new one seems to be way to solve it

cat /run/user/.1000 returns, it displays a question mark symbol but can't be copied 

\-

**Comment by jjk-jacky** [comment]
Is your /run volatile? I.e. is it a tmpfs or similar, or is it
preserved accross reboots?

If the counter file contains a dash, it means something went wrong and
it was flagged as invalid. It could be an error writing to the counter
file on session opening, but I think that's quite unlikely; but it could
also be when closing session and removing the folder, if it can't be
done for some reason then a dash is written to the counter file to
invalidate things, and further session opening won't have a variable
set.

But if /run is volatile then it obviously isn't possible on boot/first
login...

**Comment by maxice8** [comment]
Yes my /run is mounted as [tmpfs](https://github.com/voidlinux/void-runit/blob/d1de64e50fc25d9e43a479c9a74c020daa1281e4/core-services/00-pseudofs.sh#L6)

**Comment by jjk-jacky** [comment]
Well then, I think it would only leave an error during write_counter(),
specifically the write() call failing, but I can't see why that'd
happen, esp. on tmpfs... so probably something else is going on there,
though I have no idea what ATM...

**Comment by maxice8** [comment]
Yeah i'll close this for now since it seems to be very random and only happened on my voidlinux glibc system and not on my Alpine one, pretty weird.

if it becomes a non-repeating ocourrence i'll open again
