### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by vitorhugomattos** [jjk-jacky/pam_rundir#3]
simply don't work. i'm using Void and tried to install from xbps repositories. nothing. so, i tried to compile it (it requires pam-devel to <include pam_modules.h>, by the way), and nothing too :/ may i have será something more? (like the "session optional pam_rundir.so"? o didnt know where to set it).

**Comment by jjk-jacky** [comment]
Obvisouly, you're wrong, it works as expected.

Of course you need to set it up correctly, as with any PAM modules;
E.g. add it in /etc/pam.conf or something similar, depending on your
system/setup.

**Comment by cpixl** [comment]
Unfortunately I'm having the same issue, also similar to #2: The module is successfully loaded by PAM (from `/etc/pam.d/system-login`), it creates the `/run/user/.1000`files and increases/decreases the counter according to my sessions created/destroyed on the TTYs, but the `/run/user/1000` directory is never created and the `$XDG_RUNTIME_DIR` is never set. I'm also on Void Linux using the [available package](https://github.com/voidlinux/void-packages/tree/master/srcpkgs/pam_rundir).

I didn't see any error in the logs, so I'll try to debug the code and I hope to find the issue.

**Comment by vitorhugomattos** [comment]
Just installed ConsoleKit2 (now I changed to elogind) and I didn't need this program anymore.

**Comment by jjk-jacky** [comment]
(Sorry about the delay, I've been having connectivity issues lately...)


Well, if there is a bug in there somewhere I'd be happy to fix it, but
obviously something more than "don't work" will be needed.

If you manage to find something let me know and I'll see what I can do.
Based on what you describe though it seems quite odd: you're saying the
counter file is created/updated, but the directory never created, so
looking at the code that would mean the mkdir() call is failing for
some reason, unless the seteuid() failed before that. Not that I can
think of a reason why any of those would fail...

**Comment by cpixl** [comment]
@jjk-jacky I still didn't debug it properly, but I've noticed the following:

Void Linux already comes with `/run/user` directory (without the **s** at the end, as the default value) with `0755` `root:root` permissions/ownership, and the `pam_rundir` package uses `--with-parentdir=/run/user` on `./configure`. 

When building it manually with `--with-parentdir=/run/users` (the default value) it creates `/run/users` with **0775** permissions (different than the 0755 on `/run/user`), and the `root:root` ownership, and the `/run/users/1000` directory is successfully created along with the `.1000` counter correctly set too.

**Comment by cpixl** [comment]
Okay, I checked it a bit further and it seems completely related to the directory permissions:
* I login on tty1
* `ls /run/user` => `/run/user/.1000` only (= 1)
* I login on tty2
* `ls /run/user` => `/run/user/.1000` only (= 2)
* still on tty2, `sudo chmod 0775 /run/user`
* I login on tty3
* `ls /run/user` => **`/run/user/1000` directory and `/run/user/.1000` file (= 3)**

I don't know if changing `/run/user` permissions would really be the right solution here, so I ask: why exactly does it require group-writable permissions? The process will be running as `root` user anyway, won't it?

**Comment by jjk-jacky** [comment]
Ah ok, yes that makes sense. So the thing is, pam_rundir does drop
privileges (seteuid) before mkdir, to ensure either it fails, or is
created with proper ownership, to avoid all kinds of race conditions &
other complications I'm not willing to deal/bother with.

Side effect though: permission checks are enforced, and if your parent
dir isn't writable indeed the mkdir call will fail. We're still talking
about group root here, so I don't think having it group writable
would be much of a security risk.

If you really don't wanna change that, you can try the attached patch,
using prctl so permission checks are bypassed. I believe that should
have the mkdir call succeed and everything working as expected.

**Comment by jjk-jacky** [comment]
In case the parent dir (e.g. /run/user) isn't group writable, this will
allow mkdir to still succeed.

Signed-off-by: Olivier Brunel <jjk@jjacky.com>
---
 pam_rundir.c | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/pam_rundir.c b/pam_rundir.c
index 2d2c201..51082b7 100644
--- a/pam_rundir.c
+++ b/pam_rundir.c
@@ -24,6 +24,8 @@
 #include <sys/types.h>
 #include <sys/stat.h>
 #include <sys/file.h>
+#include <sys/prctl.h>
+#include <linux/securebits.h>
 #include <string.h>
 #include <pwd.h>
 #include <fcntl.h>
@@ -396,6 +398,9 @@ pam_sm_open_session (pam_handle_t *pamh, int flags, int argc, const char **argv)
             goto done;
         }
 
+        /* to bypass permission checks for mkdir, in case it isn't group
+         * writable */
+        prctl (PR_SET_SECUREBITS, SECBIT_NO_SETUID_FIXUP);
         /* set euid so if we do create the dir, it is own by the user */
         if (seteuid (pw->pw_uid) < 0)
         {
-- 
2.15.1

**Comment by cpixl** [comment]
After applying this patch, it works perfectly!

Are you planning to merge this patch in the code? If you don't, I'll add it to the Void Linux package.

**Comment by jjk-jacky** [comment]
> After applying this patch, it works perfectly!

Good to know.


> Are you planning to merge this patch in the code? If you don't, I'll
> add it to the Void Linux package.
 
Yes, I think I'll commit it; Though I'm not sure when a new release
will be done, so feel free to patch in up in the mean time.

And thanks for your help solving this.

**Comment by cpixl** [comment]
Great, thank you!

**Comment by ghost** [comment]
@jjk-jacky the patch you proposed introduces security vulnerabilities in `setuid` - namely a process is not able to drop permissions by `setuid` (and many rely on it being able to) (void-linux/void-packages#4417)

I think a better solution would be to try to `chmod` the directory to give it group write permissions instead. I'm working on a PR and I'll submit it when I'm finished testing.

**Comment by ghost** [comment]
Finished the PR. Sorry for the above spam - I was making changes in my fork and didn't realize that triggered here.

**Comment by jjk-jacky** [comment]
I don't like the chmod solution, especially the idea of changing
permissions of the pre-existing parent directory.

Leaving the securebits changed was indeed a security issue, I've just
pushed a fix for that on branch next.

Thanks for the report!

**Comment by concatime** [comment]
Using `pam_rundir.c` from next branch, I still have the folder `/run/user/.1000` owned by root, along with the correct one (`/run/user/1000`).
